name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - name: Build all example sketches
      uses: Legion2/arduino-builder-action@v2.0.0
      with:
        board: "arduino:avr:uno"
        sketch: sketch_mar07a.ino
        libraries: "https://github.com/FastLED/FastLED/archive/3.3.3.zip"
